version: "3.9"
services:
  app:
    build: ./infra/php
    volumes:
      - ./:/var/www/html

  web:
    image: nginx:1.20-alpine
    ports:
      - 8080:80
    volumes:
      - ./:/var/www/html
      - ./infra/nginx/default.conf:/etc/nginx/conf.d/default.conf
    working_dir: /var/www/html